# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, '/home/claude/farm')
from crops import CROPS, FAMILY_NAME, ALLOT, HOPS, FLOWER, HERB, BUSH, TREE, FRUIT, CACTUS, CALQUAT, MUSH, BELLA, SPIRIT

OUT = '/home/claude/farm/out'
os.makedirs(OUT + '/configs', exist_ok=True)
os.makedirs(OUT + '/scripts', exist_ok=True)

# ---------------------------------------------------------------- patch table
# (index, loc name, varp holding its state, slot within that varp, bit width, family)
PATCHES = []
def add(locs, varp, width, fam):
    for slot, loc in enumerate(locs):
        PATCHES.append(dict(i=len(PATCHES), loc=loc, varp=varp, slot=slot, width=width, fam=fam))

add(['farming_veg_patch_%d' % n for n in (1,2,3,4)], 'farming_allotment_varp_1', 8, ALLOT)
add(['farming_veg_patch_%d' % n for n in (5,6,7,8)], 'farming_allotment_varp_2', 8, ALLOT)
add(['farming_hops_patch_%d' % n for n in (1,2,3,4)], 'farming_hops_varp', 8, HOPS)
add(['farming_flower_patch_%d' % n for n in (1,2,3,4)], 'farming_flower_varp', 8, FLOWER)
add(['farming_herb_patch_%d' % n for n in (1,2,3,4)], 'varp_515', 8, HERB)
add(['farming_bush_patch_%d' % n for n in (1,2,3,4)], 'farming_bush_varp', 8, BUSH)
add(['farming_tree_patch_%d' % n for n in (1,2,3,4)], 'farming_tree_varp', 8, TREE)
add(['farming_fruit_tree_patch_%d' % n for n in (1,2,3,4)], 'farming_fruit_tree_varp', 8, FRUIT)
add(['farming_spirit_tree_patch_1','farming_spirit_tree_patch_2','farming_spirit_tree_patch_3',
     'farming_calquat_tree_patch'], 'farming_special_tree_varp', 6, None)
add(['farming_cactus_patch','farming_mushroom_patch','farming_belladonna_patch'], 'varp_512', 6, None)
add(['farming_compost_bin_%d' % n for n in (1,2,3,4)], 'varp_511', 8, None)

for p in PATCHES:
    if p['fam'] is None:
        p['fam'] = {'farming_spirit_tree_patch_1': SPIRIT, 'farming_spirit_tree_patch_2': SPIRIT,
                    'farming_spirit_tree_patch_3': SPIRIT, 'farming_calquat_tree_patch': CALQUAT,
                    'farming_cactus_patch': CACTUS, 'farming_mushroom_patch': MUSH,
                    'farming_belladonna_patch': BELLA}.get(p['loc'], 0)

N = len(PATCHES)
COMPOST_FIRST = next(p['i'] for p in PATCHES if p['loc'].startswith('farming_compost_bin'))

HDR = ("// GENERATED by tools/farming/gen.py - do not hand-edit; regenerate instead.\n"
       "// Corey, 2026-09-05. See claude/farming-skill.md.\n\n")

# ================================================================ farming.varp
v = [HDR.replace('//', '//'),
     "// Two server-side varps per patch. They are NOT transmitted: the client only ever needs the\n"
     "// appearance varbit (which already exists in the cache), so everything below stays server-side.\n"
     "//\n"
     "// farming_time_N   - world minute at which this patch last advanced a growth stage.\n"
     "// farming_flags_N  - bits 0-5 crop id (0 = empty), 6-8 harvest lives, 9-10 compost tier,\n"
     "//                    bit 11 protected by a farmer, bit 12 checked (trees/bushes claimed their xp).\n"]
for p in PATCHES:
    v.append("[farming_time_%d]\nscope=perm\n" % p['i'])
    v.append("[farming_flags_%d]\nscope=perm\n" % p['i'])
v.append("// Last world minute the whole farming state was brought up to date for this player.\n"
         "[farming_last_tick]\nscope=perm\n")
v.append("""// Tool leprechaun storage. He keeps things for you anywhere in the world, so this is one
// player-wide store rather than one per farming area.
//   bits 0-2 rakes, 3-5 seed dibbers, 6-8 spades, 9-11 gardening trowels, 12-14 secateurs,
//   bits 15-18 watering can (0 = none stored, 1..9 = a can holding 0..8 doses)
[farming_store_tools]
scope=perm
""")
v.append("// World minute the last tree seedling was watered. One value covers every seedling in the\n// inventory: they all take the same five minutes, so the only effect of sharing it is that a\n// second seedling watered while the first is still going finishes at the same time as it.\n[farming_seedling_time]\nscope=perm\n")
v.append("[farming_store_buckets]\nscope=perm\n")
v.append("[farming_store_compost]\nscope=perm\n")
v.append("[farming_store_supercompost]\nscope=perm\n")
v.append("[farming_store_curepot]\nscope=perm\n")
open(OUT + '/configs/farming.varp', 'w').write('\n'.join(v))

# ================================================================ farming.constant
k = [HDR,
"// Patch families.\n"]
for f, n in sorted(FAMILY_NAME.items()):
    k.append("^farming_family_%s = %d" % (n, f))
k.append("\n// Patch indices, in the same order as the accessor switches below.")
for p in PATCHES:
    k.append("^farming_patch_%s = %d" % (p['loc'].replace('farming_', ''), p['i']))
k.append("\n^farming_patch_count = %d" % N)
k.append("^farming_compost_bin_first = %d" % COMPOST_FIRST)
k.append("""
// Weeds. State 0 is a fully overgrown patch, 3 is bare soil ready to plant; raking counts up,
// weeds regrow counting down. Regrowth is deliberately slow so a patch you cleared last night is
// still usable in the morning.
^farming_state_weeds_full = 0
^farming_state_weeded = 3
^farming_weed_regrow_minutes = 100

// Condition, as stored implicitly by which state block the patch is sitting in.
^farming_healthy = 0
^farming_diseased = 1
^farming_dead = 2
// Not a real condition, but what a chopped-down tree leaves behind until it is dug out.
^farming_stump = 3

// Compost tiers.
^farming_compost_none = 0
^farming_compost_normal = 1
^farming_compost_super = 2

// Base harvest lives before compost. Compost adds 1, supercompost adds 2.
^farming_base_lives = 3

// Disease is rolled out of 128 once per growth cycle, except on the cycle that finishes the crop.
^farming_disease_scale = 128
^farming_compost_disease_num = 1
^farming_compost_disease_div = 2
^farming_supercompost_disease_num = 1
^farming_supercompost_disease_div = 5

// Chance-to-save is out of 256, interpolated from cts_low at level 1 to cts_high at 99.
// Both are stored x10 on the seed so the published half-points survive.
^farming_cts_scale = 256
^farming_magic_secateurs_num = 11
^farming_magic_secateurs_div = 10

// How often a logged-in player's patches are brought up to date. 100 ticks = 60s, and since every
// growth cycle is a multiple of 5 minutes nothing can be missed at this resolution.
^farming_tick_interval = 100

// Compost bin: 15 items in, one rot cycle, 15 buckets out.
^farming_compost_bin_size = 15
^farming_compost_rot_minutes = 45
^farming_compost_xp = 45
^farming_supercompost_xp = 85
^farming_rake_xp = 40

// Compost bin states inside its own 8-bit varbit: 0 empty/open, 1..15 filling, 16 closed+rotting,
// 17 rotted compost ready, 18 rotted supercompost ready. The bin loc's own multiloc only draws
// open/closed/full, so anything above 16 renders as a closed bin until it is opened.
^farming_bin_empty = 0
^farming_bin_rotting = 16
^farming_bin_compost = 17
^farming_bin_supercompost = 18

// Speed knob for testing. Every growth cycle is divided by this, so 10 turns a 40-minute allotment
// into 4 minutes. 1 = authentic. ::~farmgrow forces one cycle on every patch regardless.
^farming_speed_divisor = 1
""")
open(OUT + '/configs/farming.constant', 'w').write('\n'.join(k))

# ================================================================ farming.param
prm = [HDR,
"""// Crop data lives on the seed (or, for trees and fruit trees, on the sapling you actually plant),
// so "what does this seed grow into" is one oc_param lookup rather than a switch with 56 arms.
//
// Every *_state value below was read out of the 377 cache's multiloc tables, not invented. The rule
// they all follow is: visible state = base_state + stage, with stage 0 = just planted and
// stage == stages = fully grown. Diseased and dead blocks are indexed by stage - 1.
""",
"""// Which patch a farming loc is. Added to every patch and compost bin in
// skill_farming/configs/farming.loc so that one set of triggers can serve all 43 of them.
[farming_patch]
type=int
default=0
""",
"// Non-zero marks an item as plantable, and identifies the crop everywhere else.\n[farming_crop]\ntype=int\ndefault=0\n",
"// One of ^farming_family_*.\n[farming_family]\ntype=int\ndefault=0\n",
"[farming_level]\ntype=int\ndefault=1\n",
"// All xp values are stored x10 so 8.5 xp survives as 85.\n[farming_plant_xp]\ntype=int\ndefault=0\n",
"[farming_harvest_xp]\ntype=int\ndefault=0\n",
"// Awarded once, for the Check-health action on trees, fruit trees, bushes, cactus and calquat.\n[farming_check_xp]\ntype=int\ndefault=0\n",
"// Number of growth cycles from planted to fully grown.\n[farming_stages]\ntype=int\ndefault=4\n",
"// Minutes per growth cycle.\n[farming_cycle]\ntype=int\ndefault=10\n",
"[farming_base_state]\ntype=int\ndefault=0\n",
"[farming_diseased_state]\ntype=int\ndefault=0\n",
"[farming_dead_state]\ntype=int\ndefault=0\n",
"// 0 where the family cannot be watered.\n[farming_watered_state]\ntype=int\ndefault=0\n",
"// First state of the harvest-count run that follows fully-grown, for crops that hold produce.\n[farming_produce_state]\ntype=int\ndefault=0\n",
"// How many berries/fruit/spines the crop holds when full.\n[farming_produce_max]\ntype=int\ndefault=0\n",
"[farming_produce]\ntype=namedobj\ndefault=null\n",
"// Chance-to-save endpoints, x10, out of 256.\n[farming_cts_low]\ntype=int\ndefault=0\n",
"[farming_cts_high]\ntype=int\ndefault=0\n",
"// Disease chance per vulnerable cycle, out of 128. 0 = cannot be diseased.\n[farming_disease]\ntype=int\ndefault=0\n",
"// What the patch's farmer wants, and how many. null = this crop cannot be protected.\n[farming_protect_obj]\ntype=namedobj\ndefault=null\n",
"[farming_protect_count]\ntype=int\ndefault=0\n",
"// Seeds consumed to plant one patch.\n[farming_seed_count]\ntype=int\ndefault=1\n",
"// What a fully grown but unchecked tree/bush/cactus shows, i.e. the Check-health appearance.\n// 0 where the family has no check action.\n[farming_check_state]\ntype=int\ndefault=0\n",
"// What it shows once checked. For ordinary trees this is a second fully-grown model carrying\n// Chop down; for everything else it is the plain fully-grown state.\n[farming_checked_state]\ntype=int\ndefault=0\n",
"// What is left after a tree is chopped down, cleared with a spade. 0 where there is no stump.\n[farming_stump_state]\ntype=int\ndefault=0\n",
]
open(OUT + '/configs/farming.param', 'w').write('\n'.join(prm))

# ================================================================ obj param patch lines
objlines = {}
for c in CROPS:
    L = ["param=farming_crop,%d" % c['id'],
         "param=farming_family,%d" % c['fam'],
         "param=farming_level,%d" % c['level'],
         "param=farming_plant_xp,%d" % c['plant'],
         "param=farming_stages,%d" % c['stages'],
         "param=farming_cycle,%d" % c['cycle'],
         "param=farming_base_state,%d" % c['base'],
         "param=farming_diseased_state,%d" % c['dis'],
         "param=farming_dead_state,%d" % c['dead']]
    if c['harvest']:  L.append("param=farming_harvest_xp,%d" % c['harvest'])
    if c['check']:    L.append("param=farming_check_xp,%d" % c['check'])
    if c['wat']:      L.append("param=farming_watered_state,%d" % c['wat'])
    if c['pbase']:    L.append("param=farming_produce_state,%d" % c['pbase'])
    if c['pmax']:     L.append("param=farming_produce_max,%d" % c['pmax'])
    if c['produce']:  L.append("param=farming_produce,%s" % c['produce'])
    if c['cts_low']:  L.append("param=farming_cts_low,%d" % c['cts_low'])
    if c['cts_high']: L.append("param=farming_cts_high,%d" % c['cts_high'])
    if not c['immune'] and c['disease']: L.append("param=farming_disease,%d" % c['disease'])
    if c['prot']:
        L.append("param=farming_protect_obj,%s" % c['prot'])
        L.append("param=farming_protect_count,%d" % c['pq'])
    if c['seeds'] != 1: L.append("param=farming_seed_count,%d" % c['seeds'])
    if c['chk']:   L.append("param=farming_check_state,%d" % c['chk'])
    if c['chkd']:  L.append("param=farming_checked_state,%d" % c['chkd'])
    if c['stump']: L.append("param=farming_stump_state,%d" % c['stump'])
    objlines[c['seed']] = L
import json
json.dump(objlines, open('/home/claude/farm/objparams.json', 'w'), indent=1)

# ================================================================ farming_state.rs2 (generated accessors)
s = [HDR,
"""// The client renders a patch straight from its own 8-bit (6-bit for the special patches) slice of a
// farming varp. Those varbits and their multiloc tables are all original 377 cache data - this file
// is only the plumbing that reads and writes the right slice for a given patch index.
//
// rs2 has no way to index a varp by a runtime value, so every accessor is a switch. It is generated
// rather than hand-written for exactly that reason.
"""]

def switch(name, sig, body_fn, ret=None):
    out = ["[proc,%s]%s" % (name, sig), "switch_int($patch) {"]
    for p in PATCHES:
        out.append("    case ^farming_patch_%s : %s" % (p['loc'].replace('farming_', ''), body_fn(p)))
    out.append("    case default : %s" % (ret or "return;"))
    out.append("}")
    return "\n".join(out)

s.append("// The patch's visible state, as the client sees it.")
s.append(switch('farming_get_state', '(int $patch)(int)',
                lambda p: "return(getbit_range(%%%s, %d, %d));" % (p['varp'], p['slot']*p['width'], p['slot']*p['width']+p['width']-1),
                "return(0);"))
s.append("")
s.append("[proc,farming_set_state](int $patch, int $state)\nswitch_int($patch) {")
for p in PATCHES:
    a, b = p['slot']*p['width'], p['slot']*p['width']+p['width']-1
    s.append("    case ^farming_patch_%s : %%%s = setbit_range_toint(%%%s, $state, %d, %d);"
             % (p['loc'].replace('farming_', ''), p['varp'], p['varp'], a, b))
s.append("    case default : return;\n}")
s.append("")
s.append("// World minute at which this patch last advanced.")
s.append(switch('farming_get_time', '(int $patch)(int)', lambda p: "return(%%farming_time_%d);" % p['i'], "return(0);"))
s.append("")
s.append("[proc,farming_set_time](int $patch, int $time)\nswitch_int($patch) {")
for p in PATCHES:
    s.append("    case ^farming_patch_%s : %%farming_time_%d = $time;" % (p['loc'].replace('farming_',''), p['i']))
s.append("    case default : return;\n}")
s.append("")
s.append("// Packed crop id / lives / compost / protected / checked.")
s.append(switch('farming_get_flags', '(int $patch)(int)', lambda p: "return(%%farming_flags_%d);" % p['i'], "return(0);"))
s.append("")
s.append("[proc,farming_set_flags](int $patch, int $flags)\nswitch_int($patch) {")
for p in PATCHES:
    s.append("    case ^farming_patch_%s : %%farming_flags_%d = $flags;" % (p['loc'].replace('farming_',''), p['i']))
s.append("    case default : return;\n}")
s.append("")
s.append("// Which family of crop this patch grows. Constant per patch, so it lives here rather than in a varp.")
s.append(switch('farming_patch_family', '(int $patch)(int)',
                lambda p: "return(^farming_family_%s);" % FAMILY_NAME.get(p['fam'], 'allotment') if p['fam'] else "return(0);",
                "return(0);"))
open(OUT + '/scripts/farming_state.rs2', 'w').write('\n'.join(s) + '\n')

json.dump(PATCHES, open('/home/claude/farm/patches_table.json', 'w'), indent=1)
print("patches:", N, "compost first:", COMPOST_FIRST, "crops:", len(CROPS))
