# -*- coding: utf-8 -*-
import sys, os, json
sys.path.insert(0, '/home/claude/farm')
from crops import CROPS, FAMILY_NAME
OUT = '/home/claude/farm/out'
PATCHES = json.load(open('/home/claude/farm/patches_table.json'))

HDR = ("// GENERATED by tools/farming/gen.py - do not hand-edit; regenerate instead.\n"
       "// Corey, 2026-09-05. See claude/farming-skill.md.\n\n")

# ------------------------------------------------------------------ crop id -> seed obj
s = [HDR,
"""// Patches store a 6-bit crop id rather than an obj id, so this is the way back to the seed (or
// sapling) that every oc_param lookup goes through. Ids are dense and assigned in the same order as
// the table in claude/farming-skill.md.
""",
"[proc,farming_crop_obj](int $crop)(namedobj)", "switch_int($crop) {"]
for c in CROPS:
    s.append("    case %-3d : return(%s); // %s" % (c['id'], c['seed'], FAMILY_NAME[c['fam']]))
s.append("    case default : return(null);\n}")
s.append("")
s.append("""// The reverse: which crop a seed or sapling plants. Kept as a param so that "is this thing
// plantable" is one lookup on any item the player shoves at a patch.
[proc,farming_seed_crop](obj $seed)(int)
if ($seed = null) {
    return(0);
}
return(oc_param($seed, farming_crop));""")
open(OUT + '/scripts/farming_crops.rs2', 'w').write('\n'.join(s) + '\n')

# ------------------------------------------------------------------ triggers
t = [HDR,
"""// Every patch loc carries category=_farming_patch and param=farming_patch,<index>, added to
// skill_farming/configs/farming.loc, so one set of triggers covers all 39 patches instead of 39 sets.
//
// A patch on the map is a multiloc: the client picks the appearance from the patch's varbit and takes
// the right-click options from THAT appearance (Harvest, Check-health, Pick-fruit, Chop-down and so
// on, all already authored in the cache), but the loc id it sends back is the parent patch. So the
// op number that arrives here means different things depending on the patch's current state, and
// every op1 handler starts by working out what the patch is actually showing.
//
// op2 (Inspect) and op4 (Guide) are on every appearance in the cache, so they always work.

[oploc1,_farming_patch] ~farming_op1(loc_param(farming_patch));
[oploc2,_farming_patch] ~farming_inspect(loc_param(farming_patch));
[oploc4,_farming_patch] ~farming_guide(loc_param(farming_patch));
[oplocu,_farming_patch] ~farming_useitem(loc_param(farming_patch), last_useitem, last_useslot);

[oploc1,_farming_compost_bin] ~farming_bin_op1(loc_param(farming_patch));
[oploc2,_farming_compost_bin] ~farming_bin_inspect(loc_param(farming_patch));
[oplocu,_farming_compost_bin] ~farming_bin_useitem(loc_param(farming_patch), last_useitem, last_useslot);
"""]
open(OUT + '/scripts/farming_triggers.rs2', 'w').write('\n'.join(t) + '\n')

# ------------------------------------------------------------------ farming.loc edits
edits = {}
for p in PATCHES:
    # NOTE: no leading underscore here. The '_' in [oploc1,_farming_patch] is the compiler's
    # syntax for "this subject is a category"; the category's own name has no underscore.
    cat = 'farming_compost_bin' if p['loc'].startswith('farming_compost_bin') else 'farming_patch'
    edits[p['loc']] = ["category=%s" % cat, "param=farming_patch,%d" % p['i']]
json.dump(edits, open('/home/claude/farm/locedits.json', 'w'), indent=1)
print("generated:", len(CROPS), "crops,", len(edits), "loc edits")
